### PR TITLE
[ADD][9.0][BR000778][T20115] Improve the calculation of current Payroll rules 

### PR DESCRIPTION
**Pull request by dongshukai**
@elicoidal 
I modify the salary rule about SH (Foreigner W/ SI), please check it. thanks

### CODE REVIEW

**Review by elicoidal — COMMENTED** [review]
This looks ok to me but dont you need to change the version number?
Besides it needs to be tested before merge

**Comment by dongshukai** [comment]
This PR is a part of the BR000778, so the version number is changed already.
Besides, If I want test the PR, which environment I should use? the OCA runbot I can't login with my Github account or LDAP account, and our company runbot did't have the project on payroll

At 2017-06-20 17:52:42, "Eric @ Elico Corp" <notifications@github.com> wrote:


@elicoidal commented on this pull request.

This looks ok to me but dont you need to change the version number?
Besides it needs to be tested before merge

**Comment by elicoidal** [comment]
You should be able to use OCA runbot. If not working then we need to set it up.I will be back this afternoon: we can check it together if necessary

**Comment by dongshukai** [comment]
@elicoidal Linda has test the PR and said it is ok.

**Comment by elicoidal** [comment]
@dongshukai 
OK: I will deploy it in our trunk environment
Thanks!

**Review by elicoidal — APPROVED** [review]

**Pull request merged**
