### PR TITLE
[WIP][9.0] BR000778 - ts20115 Improve the calculation of current Payroll rules

### PR DESCRIPTION
**Pull request by Wizr**
@oca-clabot  @elicoidal

### CODE REVIEW

**Comment by elicoidal** [comment]
I will take care of the CLA (from Elico)

**Comment by elicoidal** [comment]
To be tested by Linda when the runbot is fixed

**Comment by Wizr** [comment]
@victormartinelicocorp codecov report that `No report found to compare against`, could you help with this?

cc @elicoidal

**Comment by martintorresvm** [comment]
> victormartinelicocorp codecov report that No report found to compare against, could you help with this?
 cc elicoidal

What you need to do is close this PR.

Create a branch on you repository based on the master branch you want to point
Add/remove your code
Commit
Push your repository on Git
GitHub https://github.com/OCA/l10n-china will detect you want to create a PR
Then you just need to click on the button create a Pull Request

cc @elicoidal @seb-elico

**Comment by Wizr** [comment]
@victormartinelicocorp ok, i got it. I will close this PR now.

**Pull request closed without merging**
